[package]
name = "embassy_gps"
version = "0.1.0"
edition = "2024"
description = "Lightweight Embassy GPS wrapper and extensible architecture"
readme = "README.md"
license = "AGPL-3.0-or-later"
keywords = ["embassy", "gps", "embedded", "no-std"]
categories = ["embedded", "no-std", "asynchronous"]

[features]
default = []

nrf = [
    "dep:embassy-nrf",
]

# internal flag: common dependencies of all ESP32 variants
_esp = ["dep:esp-hal"]
# build for ESP32
esp32       = ["_esp", "esp-hal/esp32"]
# build for ESP32-C2
esp32c2     = ["_esp", "esp-hal/esp32c2"]
# build for ESP32-C3
esp32c3     = ["_esp", "esp-hal/esp32c3"]
# build for ESP32-C5
esp32c5     = ["_esp", "esp-hal/esp32c5"]
# build for ESP32-C6
esp32c6     = ["_esp", "esp-hal/esp32c6"]
# build for ESP32-C61
esp32c61    = ["_esp", "esp-hal/esp32c61"]
# build for ESP32-H2
esp32h2     = ["_esp", "esp-hal/esp32h2"]
# build for ESP32-S2
esp32s2     = ["_esp", "esp-hal/esp32s2"]
# build for ESP32-S3
esp32s3     = ["_esp", "esp-hal/esp32s3"]


[dependencies]
chrono = { version = "0.4", default-features = false }
defmt = "1"
embassy-futures = "0.1.2"
embassy-nrf = { version = "0.10", optional = true, features = ["defmt", "time-driver-rtc1", "gpiote", "nrf52840"] }
embassy-time = { version = "0.5", features = ["defmt"] }
embedded-io-async = { version = "0.7.0", features = ["defmt"] }
heapless = {version = "0.9.2", features = ["defmt"] }
nmea = { version = "0.7.0", default-features = false, features = ["GGA", "RMC"] }
esp-hal = { version = "1.0.0", optional = true }
